services:
  server:
    build: ./spigot-server
    ports:
      - "25565:25565"
    volumes:
      - world-data:/app/data
      - key-path:/app/plugins/floodgate-bukkit/
  gateway:
    build: ./geyser-standalone
    ports: 
      - "19133:19132"
    volumes:
      - key-path:/app/floodgate-bukkit
  bedrock-connect:
    build: ./bedrock-connect
    ports:
      - "19132:19132"
volumes:
  world-data: {}
  key-path: {}